"""The fictional company. Every name here is invented; any resemblance to a real organisation is accidental."""

from dataclasses import dataclass, field

COMPANY = "Norvane Automotive Systems"

PLANTS = {
    "PN2": "Pune Plant 2 (India)",
    "CHN": "Chennai Plant (India)",
    "TLC": "Toluca Plant (Mexico)",
    "KRK": "Krakow Plant (Poland)",
}

# component code -> (product line, display name)
COMPONENTS = {
    "RAD": ("thermal", "radiator"),
    "HVC": ("thermal", "HVAC module"),
    "CMP": ("thermal", "electric compressor"),
    "INJ": ("powertrain", "fuel injector"),
    "SNS": ("powertrain", "sensor"),
    "INV": ("electrification", "traction inverter"),
    "DCD": ("electrification", "DC-DC converter"),
    "BMS": ("electrification", "BMS ECU"),
    "WPM": ("body_electronics", "wiper motor"),
    "EPS": ("body_electronics", "EPS motor"),
}

PRODUCT_LINES = {
    "thermal": "Thermal Systems",
    "powertrain": "Powertrain Components",
    "electrification": "Electrification",
    "body_electronics": "Body Electronics",
}

OEMS = ["Orion Motors", "Vesta Automobiles", "Kairo EV", "Halden Trucks"]

SUPPLIERS = {
    "TAL": ("Talvik Alloys", "aluminium brazing sheet and tubes"),
    "VLX": ("Veltrix Polymers", "injection-moulded PA66 / POM parts"),
    "BOM": ("Brandt-Ostwald Magnetics", "sintered NdFeB magnets"),
    "LPW": ("Lumen PCB Works", "PCB assemblies"),
    "SCS": ("Seacrest Seals", "O-rings and elastomer gaskets"),
    "APD": ("Ardent Power Devices", "IGBT and SiC power modules"),
    "QTC": ("Qiantai Ceramics", "MLCC and film capacitors"),
    "MWC": ("Morrow Wire & Cable", "terminals, connectors and harnesses"),
    "CBR": ("Castell Bearings", "ball bearings"),
    "HLS": ("Heliot Sensors", "thermistors and sensing elements"),
}

PEOPLE = [
    "R. Kulkarni",
    "A. Menon",
    "J. Hernandez",
    "M. Nowak",
    "S. Iyer",
    "K. Tanaka",
    "L. Garcia",
    "P. Wisniewski",
    "D. Rao",
    "F. Okafor",
    "T. Sato",
    "N. Deshpande",
    "E. Kowalczyk",
    "V. Pillai",
    "C. Ruiz",
    "H. Lindqvist",
]


@dataclass
class Project:
    code: str
    name: str
    comp: str
    oem: str
    plant: str
    sop: int


PROJECTS = [
    Project("P-RAD-2101", "Compact radiator for C-segment SUV", "RAD", "Orion Motors", "CHN", 2021),
    Project("P-RAD-2204", "Heavy-duty radiator for 7.5 t truck", "RAD", "Halden Trucks", "TLC", 2022),
    Project("P-HVC-2102", "Dual-zone HVAC module", "HVC", "Vesta Automobiles", "KRK", 2021),
    Project("P-HVC-2203", "Rear HVAC module for MPV", "HVC", "Orion Motors", "PN2", 2022),
    Project("P-CMP-2201", "400 V electric A/C compressor", "CMP", "Kairo EV", "KRK", 2022),
    Project("P-CMP-2402", "800 V electric A/C compressor", "CMP", "Kairo EV", "CHN", 2024),
    Project("P-INJ-2001", "GDI injector 350 bar", "INJ", "Vesta Automobiles", "PN2", 2020),
    Project("P-INJ-2203", "Port-fuel injector for flex-fuel engines", "INJ", "Orion Motors", "TLC", 2022),
    Project("P-SNS-2002", "Exhaust gas temperature sensor", "SNS", "Halden Trucks", "KRK", 2020),
    Project("P-SNS-2201", "Manifold absolute pressure sensor", "SNS", "Vesta Automobiles", "PN2", 2022),
    Project("P-INV-2104", "150 kW SiC traction inverter", "INV", "Kairo EV", "CHN", 2021),
    Project("P-INV-2301", "80 kW IGBT traction inverter", "INV", "Orion Motors", "TLC", 2023),
    Project("P-DCD-2102", "3 kW DC-DC converter", "DCD", "Kairo EV", "PN2", 2021),
    Project("P-BMS-2103", "Battery management ECU, 96 cells", "BMS", "Kairo EV", "CHN", 2021),
    Project("P-WPM-2003", "Front wiper motor, 2-speed", "WPM", "Halden Trucks", "TLC", 2020),
    Project("P-EPS-2102", "Column EPS motor", "EPS", "Vesta Automobiles", "KRK", 2021),
]
PROJECT = {p.code: p for p in PROJECTS}


@dataclass
class Case:
    """One real-looking quality issue. Drives the 8D, lessons-learned, ECN, test report, DFMEA row, ..."""

    key: str
    project: str
    year: int
    supplier: str | None
    part: str
    part_name: str
    title: str
    short: str  # used in questions ("the ... issue")
    symptom: str
    detection: str
    root_cause: str
    rc_keys: list[str]
    containment: str
    cont_keys: list[str]
    corrective: str
    ca_keys: list[str]
    verification: str
    lesson: str
    lesson_keys: list[str]
    num_q: str  # question about a number stated in the 8D
    num_a: str
    failure_mode: str
    effect: str
    cause: str
    sod_before: tuple[int, int, int]
    sod_after: tuple[int, int, int]
    test: dict = field(default_factory=dict)  # verification test report
    ecn: dict | None = None  # {"from": ..., "to": ..., "what": ...}
    ffa: bool = False  # has a field-failure analysis
    plant: str = ""

    def __post_init__(self):
        self.plant = self.plant or PROJECT[self.project].plant

    @property
    def comp(self) -> str:
        return PROJECT[self.project].comp


CASES = [
    # ------------------------------------------------------------------ RADIATOR
    Case(
        key="rad-braze-voids",
        project="P-RAD-2101",
        year=2021,
        supplier=None,
        part="RAD-20417",
        part_name="radiator core assembly",
        title="Coolant leaks at tube-to-header joints after furnace speed increase",
        short="radiator tube-to-header coolant leak",
        symptom="Customer Orion Motors reported coolant loss on 64 vehicles within the first 3 months in service. "
        "Dye inspection located seepage at the tube-to-header joints on the inlet side of the core.",
        detection="The end-of-line air-under-water leak test at 1.0 bar did not detect the micro-leaks; they only opened "
        "after 40-60 thermal cycles in the vehicle.",
        root_cause="Brazing voids at the tube-to-header joint. The controlled-atmosphere brazing furnace belt speed had "
        "been raised from 0.9 m/min to 1.2 m/min to gain throughput, which shortened time above flux melting "
        "temperature and left insufficient fillet formation. The change was not reviewed in the PFMEA.",
        rc_keys=["brazing voids", "belt speed"],
        containment="100% helium leak test at 1.5 bar on all stock; 4,120 cores sorted at Chennai and in transit, "
        "23 leakers found and scrapped.",
        cont_keys=["helium leak test", "4,120"],
        corrective="Belt speed restored to 0.9 m/min and locked in the furnace recipe; inline vision check of flux "
        "coverage added before the furnace; SPC chart on the furnace thermal profile with a monthly profiling run.",
        ca_keys=["0.9 m/min", "flux coverage"],
        verification="No leaks in 12,000 cores produced after the change; thermal cycling on 6 samples passed.",
        lesson="A throughput change to a special process such as brazing is a design change for the joint. Any furnace "
        "recipe change must trigger a PFMEA review and a joint requalification before release.",
        lesson_keys=["PFMEA review", "requalification"],
        num_q="How many vehicles were affected by coolant loss in the radiator tube-to-header leak case?",
        num_a="64",
        failure_mode="Coolant leak at tube-to-header joint",
        effect="Engine overheating, coolant loss",
        cause="Insufficient braze fillet (voids) from furnace profile deviation",
        sod_before=(8, 5, 6),
        sod_after=(8, 2, 4),
        test={
            "type": "Thermal cycling",
            "standard": "NAS-TS-0412",
            "condition": "-40 C / +120 C coolant, 1 bar",
            "requirement": "no leak after 3,000 cycles",
            "samples": 6,
            "cycles": 3000,
            "failed": 0,
        },
    ),
    Case(
        key="rad-tank-crack",
        project="P-RAD-2204",
        year=2022,
        supplier="VLX",
        part="RAD-22950",
        part_name="plastic inlet tank",
        title="Inlet tank neck cracks caused by unapproved mould gate relocation",
        short="radiator inlet tank crack",
        symptom="Halden Trucks raised 118 warranty claims for coolant leaks; cracks initiated at the inlet neck of the "
        "PA66-GF30 tank after 8-14 months.",
        detection="Detected in the field; the existing burst test at 3 bar passed because the defect needs cyclic "
        "loading to grow.",
        root_cause="Veltrix Polymers relocated the mould gate during tool refurbishment without a change notification. "
        "The new weld line sat at the neck and the glass fibres were oriented transverse to the hoop stress, cutting "
        "fatigue strength by about 35%.",
        rc_keys=["gate", "weld line"],
        containment="Shipments switched to tanks moulded with the second (unchanged) cavity; 100% burst test at 4.5 bar "
        "for all stock.",
        cont_keys=["burst test", "4.5 bar"],
        corrective="Original gate position restored; a supplier change notification (SCN) clause for tooling changes "
        "added to the supply agreement; ECN added a 2 mm reinforcing rib around the neck.",
        ca_keys=["gate position restored", "rib"],
        verification="Pressure-temperature cycling for 3,000 cycles passed with zero cracks on 10 samples.",
        lesson="Tool refurbishment at a supplier can change part properties as much as a design change. Tooling changes "
        "must be PPAP triggers, and fibre orientation must be checked with a mould-flow simulation.",
        lesson_keys=["PPAP", "mould-flow"],
        num_q="How many warranty claims did Halden Trucks raise for the radiator inlet tank crack?",
        num_a="118",
        failure_mode="Tank neck crack",
        effect="Coolant loss, engine overheating",
        cause="Weld line at neck / fibre orientation from mould gate position",
        sod_before=(8, 6, 7),
        sod_after=(8, 2, 3),
        test={
            "type": "Pressure-temperature cycling",
            "standard": "NAS-TS-0415",
            "condition": "0.2-2.2 bar, +90 C",
            "requirement": "no crack after 3,000 cycles",
            "samples": 10,
            "cycles": 3000,
            "failed": 0,
        },
        ecn={
            "what": "inlet tank neck",
            "from": "no rib at neck",
            "to": "2 mm reinforcing rib around the neck",
        },
        ffa=True,
    ),
    Case(
        key="rad-salt-corrosion",
        project="P-RAD-2101",
        year=2023,
        supplier="TAL",
        part="RAD-20417",
        part_name="radiator core assembly",
        title="Premature fin and tube corrosion in coastal markets",
        short="radiator coastal corrosion",
        symptom="Radiators from coastal regions showed perforated tubes after about 2 years; 37 units returned.",
        detection="Detected through field returns; the neutral salt-spray test in the DVP&R did not reproduce acidic "
        "coastal exposure.",
        root_cause="The zinc diffusion layer on the tubes was too thin: Talvik Alloys supplied tube stock with 4 g/m2 "
        "zinc arc-spray instead of the specified 8 g/m2, so the sacrificial layer was consumed early.",
        rc_keys=["zinc", "4 g/m2"],
        containment="Affected coil lots quarantined; incoming zinc-coating check introduced on every coil.",
        cont_keys=["quarantined", "zinc-coating check"],
        corrective="Specification tightened to 8-10 g/m2 zinc; incoming XRF measurement of zinc load on every coil; "
        "SWAAT (acidified synthetic sea-water) test added to the DVP&R.",
        ca_keys=["XRF", "SWAAT"],
        verification="SWAAT test reached 44 days without perforation against a 40-day requirement.",
        lesson="Neutral salt spray does not represent coastal corrosion. Use SWAAT for aluminium heat exchangers sold in "
        "coastal markets and verify sacrificial coating load at incoming inspection.",
        lesson_keys=["SWAAT", "sacrificial"],
        num_q="How many days did the radiator survive in the SWAAT test after the corrosion corrective action?",
        num_a="44",
        failure_mode="Tube perforation by corrosion",
        effect="Coolant leak",
        cause="Insufficient zinc sacrificial layer on tube stock",
        sod_before=(7, 5, 6),
        sod_after=(7, 2, 3),
        test={
            "type": "SWAAT corrosion",
            "standard": "ASTM G85 A3",
            "condition": "acidified synthetic sea water, 49 C",
            "requirement": "no perforation before 40 days",
            "samples": 4,
            "cycles": 44,
            "failed": 0,
            "unit": "days",
        },
    ),
    # ------------------------------------------------------------------ HVAC
    Case(
        key="hvc-blend-door",
        project="P-HVC-2102",
        year=2021,
        supplier=None,
        part="HVC-31108",
        part_name="blend door actuator",
        title="Blend door actuator stall at low temperature",
        short="HVAC blend door actuator stall",
        symptom="Clicking noise and loss of temperature control at -30 C reported by Vesta Automobiles during winter "
        "testing in Scandinavia.",
        detection="Found in customer winter testing; the DV cold test at -30 C only cycled the door 20 times.",
        root_cause="The door grease thickened at low temperature and raised break-away torque to 0.27 Nm, while the "
        "actuator stall torque was 0.30 Nm, a margin of only 1.1x.",
        rc_keys=["grease", "margin"],
        containment="Low-temperature PAO grease introduced at the line for all new builds from week 48.",
        cont_keys=["PAO grease"],
        corrective="Actuator upgraded to 0.45 Nm stall torque and door grease changed to a PAO-based grade; torque "
        "margin is now 1.8x at -40 C.",
        ca_keys=["0.45 Nm", "PAO"],
        verification="500 door cycles at -40 C passed on 8 modules.",
        lesson="Size actuators for the worst-case temperature, not room temperature. Keep at least 1.5x torque margin at "
        "the lowest operating temperature.",
        lesson_keys=["1.5x", "worst-case temperature"],
        num_q="What was the actuator torque margin before the HVAC blend door stall fix?",
        num_a="1.1x",
        failure_mode="Actuator stall",
        effect="Loss of temperature control",
        cause="Grease viscosity increase at low temperature; insufficient torque margin",
        sod_before=(6, 5, 5),
        sod_after=(6, 2, 3),
        test={
            "type": "Cold chamber cycling",
            "standard": "NAS-TS-0220",
            "condition": "-40 C soak, door full sweep",
            "requirement": "500 cycles without stall",
            "samples": 8,
            "cycles": 500,
            "failed": 0,
        },
    ),
    Case(
        key="hvc-evap-odor",
        project="P-HVC-2203",
        year=2022,
        supplier=None,
        part="HVC-32040",
        part_name="evaporator and drain",
        title="Musty odour from HVAC evaporator in humid climates",
        short="HVAC evaporator odour",
        symptom="Orion Motors dealers in humid regions reported a musty smell at A/C start-up; 52 complaints.",
        detection="Field complaints; odour panel confirmed microbial growth on evaporator fins.",
        root_cause="Condensate drain slope of 1 degree left water standing on the evaporator; one batch was also missing "
        "the hydrophilic fin coating, so condensate formed droplets instead of draining.",
        rc_keys=["drain slope", "hydrophilic"],
        containment="Evaporator batches checked for hydrophilic coating before assembly.",
        cont_keys=["hydrophilic coating"],
        corrective="Drain slope increased from 1 to 4 degrees; incoming check of fin coating by water contact angle "
        "(must be below 20 degrees).",
        ca_keys=["4 degrees", "contact angle"],
        verification="Water retention after shut-down reduced from 38 g to 9 g.",
        lesson="Condensate management needs a drain-slope check in the design review and a coating check at incoming "
        "inspection.",
        lesson_keys=["drain slope", "coating"],
        num_q="By how much was water retention reduced after the HVAC evaporator odour fix?",
        num_a="from 38 g to 9 g",
        failure_mode="Standing condensate on evaporator",
        effect="Musty odour, customer dissatisfaction",
        cause="Insufficient drain slope; missing hydrophilic coating",
        sod_before=(5, 6, 6),
        sod_after=(5, 2, 4),
        test={
            "type": "Water retention",
            "standard": "NAS-TS-0231",
            "condition": "35 C / 80% RH, 30 min A/C",
            "requirement": "retention below 15 g",
            "samples": 5,
            "cycles": 1,
            "failed": 0,
        },
        ecn={"what": "condensate drain slope", "from": "1 degree", "to": "4 degrees"},
    ),
    Case(
        key="hvc-blower-noise",
        project="P-HVC-2102",
        year=2023,
        supplier=None,
        part="HVC-31220",
        part_name="blower scroll housing",
        title="Blower whine at speed 3 caused by housing resonance",
        short="HVAC blower whine",
        symptom="Tonal whine audible at blower speed 3 (1,850 rpm) in the cabin.",
        detection="Found in the customer NVH jury evaluation before SOP of the facelift.",
        root_cause="The impeller blade-pass frequency at 1,850 rpm coincided with a scroll housing panel mode at 740 Hz.",
        rc_keys=["740 Hz", "blade-pass"],
        containment="Blower speed 3 voltage adjusted to move operating speed to 1,700 rpm as an interim measure.",
        cont_keys=["1,700 rpm"],
        corrective="Two stiffening ribs added to the scroll housing, raising the panel mode to 910 Hz; impeller changed "
        "from 37 to 41 unevenly spaced blades.",
        ca_keys=["910 Hz", "41"],
        verification="Tonal noise at speed 3 reduced by 6 dB(A).",
        lesson="Check blade-pass frequencies against housing modes in the CAE modal analysis for every blower speed.",
        lesson_keys=["modal analysis", "blade-pass"],
        num_q="By how many dB(A) was the HVAC blower whine reduced?",
        num_a="6 dB(A)",
        failure_mode="Tonal noise",
        effect="Customer complaint (NVH)",
        cause="Blade-pass frequency coincides with housing mode",
        sod_before=(4, 5, 5),
        sod_after=(4, 2, 3),
        test={
            "type": "NVH acoustic test",
            "standard": "NAS-TS-0240",
            "condition": "semi-anechoic room, speeds 1-4",
            "requirement": "tonality below 1.5 tu",
            "samples": 3,
            "cycles": 1,
            "failed": 0,
        },
        ecn={"what": "blower scroll housing", "from": "no stiffening ribs", "to": "two stiffening ribs"},
    ),
    # ------------------------------------------------------------------ COMPRESSOR
    Case(
        key="cmp-oring-leak",
        project="P-CMP-2201",
        year=2022,
        supplier="SCS",
        part="CMP-40318",
        part_name="housing O-ring (HNBR)",
        title="Refrigerant leak at compressor housing O-ring after compound change",
        short="compressor housing O-ring leak",
        symptom="Loss of A/C cooling on 29 vehicles; refrigerant leak traced to the housing O-ring.",
        detection="Field returns and warranty analysis at Kairo EV.",
        root_cause="Seacrest Seals changed the HNBR compound filler to a cheaper grade. Compression set after 1,000 h at "
        "150 C rose to 38% against a 25% maximum, so the seal lost contact pressure.",
        rc_keys=["compression set", "38%"],
        containment="Helium leak test sensitivity tightened from 5 g/year to 2 g/year; stock sorted.",
        cont_keys=["2 g/year"],
        corrective="Original compound restored; compression-set test added to annual requalification for all elastomer "
        "parts from Seacrest Seals.",
        ca_keys=["original compound", "annual requalification"],
        verification="Compression set measured at 19% after 1,000 h at 150 C.",
        lesson="Elastomer compound changes are invisible on the drawing. Specify the compound code and require annual "
        "compression-set testing.",
        lesson_keys=["compound", "compression-set"],
        num_q="What compression set did the changed HNBR compound reach in the compressor O-ring leak case?",
        num_a="38%",
        failure_mode="Refrigerant leak at housing seal",
        effect="Loss of A/C performance",
        cause="Seal compression set from compound change",
        sod_before=(7, 5, 6),
        sod_after=(7, 2, 4),
        test={
            "type": "Compression set",
            "standard": "ISO 815-1",
            "condition": "150 C, 1,000 h, 25% deflection",
            "requirement": "compression set 25% max",
            "samples": 5,
            "cycles": 1000,
            "failed": 0,
            "unit": "h",
        },
    ),
    Case(
        key="cmp-pd-insulation",
        project="P-CMP-2402",
        year=2024,
        supplier=None,
        part="CMP-41502",
        part_name="stator winding",
        title="Stator insulation breakdown on 800 V compressor with SiC drive",
        short="800 V compressor stator insulation breakdown",
        symptom="Two DV samples failed with phase-to-ground shorts after 600 h of endurance at 850 V.",
        detection="Found in design validation endurance testing.",
        root_cause="Partial discharge in the enamel wire insulation. The SiC inverter switches at 15 kV/us and doubles "
        "voltage overshoot at the motor terminals, exceeding the enamel's partial-discharge inception voltage (PDIV) "
        "of 1,050 V.",
        rc_keys=["partial discharge", "PDIV"],
        containment="Endurance testing paused; build of further DV samples stopped.",
        cont_keys=["paused"],
        corrective="Corona-resistant enamel wire with PDIV above 1,500 V; partial-discharge test added to the DVP&R and "
        "as a 100% end-of-line test.",
        ca_keys=["corona-resistant", "1,500 V"],
        verification="Endurance of 2,000 h at 850 V passed on 6 samples with no partial discharge.",
        lesson="800 V platforms with SiC drives need partial-discharge testing on every winding; 400 V insulation designs "
        "cannot be carried over.",
        lesson_keys=["partial-discharge", "800 V"],
        num_q="What was the PDIV of the original enamel wire in the 800 V compressor insulation failure?",
        num_a="1,050 V",
        failure_mode="Winding insulation breakdown",
        effect="Compressor failure, loss of A/C",
        cause="Partial discharge from fast dv/dt voltage overshoot",
        sod_before=(8, 6, 5),
        sod_after=(8, 2, 3),
        test={
            "type": "Partial discharge endurance",
            "standard": "IEC 60034-18-41",
            "condition": "850 V DC link, SiC drive",
            "requirement": "no PD, 2,000 h",
            "samples": 6,
            "cycles": 2000,
            "failed": 0,
            "unit": "h",
        },
        ecn={
            "what": "stator winding wire",
            "from": "standard enamel wire (PDIV 1,050 V)",
            "to": "corona-resistant enamel wire (PDIV above 1,500 V)",
        },
    ),
    Case(
        key="cmp-scroll-wear",
        project="P-CMP-2201",
        year=2023,
        supplier=None,
        part="CMP-40210",
        part_name="orbiting scroll",
        title="Scroll wear from poor oil return at low refrigerant charge",
        short="compressor scroll wear",
        symptom="Rising noise and falling capacity on 17 compressors returned from fleet vehicles.",
        detection="Fleet customer returns; teardown showed scroll tip wear.",
        root_cause="At low refrigerant charge and low speed, oil did not return to the compressor, so the scroll tips ran "
        "without lubrication.",
        rc_keys=["oil return", "low refrigerant charge"],
        containment="Service bulletin to check refrigerant charge on fleet vehicles.",
        cont_keys=["service bulletin"],
        corrective="Internal oil separator redesigned and a minimum compressor speed of 1,500 rpm set in software.",
        ca_keys=["oil separator", "1,500 rpm"],
        verification="Low-charge endurance test at 60% charge passed 1,200 h.",
        lesson="Test compressors at degraded refrigerant charge, not just nominal, because real fleets lose charge.",
        lesson_keys=["degraded refrigerant charge"],
        num_q="What minimum compressor speed was set in software to fix scroll wear?",
        num_a="1,500 rpm",
        failure_mode="Scroll tip wear",
        effect="Noise, loss of capacity",
        cause="Insufficient oil return at low charge",
        sod_before=(6, 4, 6),
        sod_after=(6, 2, 4),
        test={
            "type": "Low-charge endurance",
            "standard": "NAS-TS-0302",
            "condition": "60% refrigerant charge",
            "requirement": "1,200 h without wear beyond 20 um",
            "samples": 3,
            "cycles": 1200,
            "failed": 0,
            "unit": "h",
        },
    ),
    # ------------------------------------------------------------------ INJECTOR
    Case(
        key="inj-coking",
        project="P-INJ-2001",
        year=2021,
        supplier=None,
        part="INJ-50117",
        part_name="GDI injector nozzle",
        title="Nozzle coking and flow loss on the new cylinder head",
        short="GDI injector nozzle coking",
        symptom="Rough idle and misfire codes after about 60,000 km; injector flow loss of 7% measured on returns.",
        detection="Field returns from Vesta Automobiles.",
        root_cause="The new cylinder head placed the nozzle tip 20 C hotter than on the previous engine, which "
        "accelerated deposit formation in the spray holes.",
        rc_keys=["20 C hotter", "deposit"],
        containment="Customer service campaign with injector cleaning for affected vehicles.",
        cont_keys=["injector cleaning"],
        corrective="Spray-hole geometry changed to a conical shape (k-factor 1.5 to 2.0) and a heat shield sleeve added.",
        ca_keys=["k-factor", "heat shield"],
        verification="Engine dyno coking cycle showed flow loss below 2%.",
        lesson="A new cylinder head is a new environment for the injector: re-run the tip-temperature measurement and the "
        "coking test even when the injector is carried over.",
        lesson_keys=["tip-temperature", "carried over"],
        num_q="What injector flow loss was measured on returned parts in the GDI nozzle coking case?",
        num_a="7%",
        failure_mode="Spray hole coking",
        effect="Misfire, rough idle, emissions",
        cause="High nozzle tip temperature",
        sod_before=(7, 5, 6),
        sod_after=(7, 2, 4),
        test={
            "type": "Dyno coking cycle",
            "standard": "NAS-TS-0510",
            "condition": "tip temperature 180 C, 200 h",
            "requirement": "flow loss below 3%",
            "samples": 4,
            "cycles": 200,
            "failed": 0,
            "unit": "h",
        },
        ecn={
            "what": "spray-hole geometry",
            "from": "cylindrical holes (k-factor 1.5)",
            "to": "conical holes (k-factor 2.0) with heat shield sleeve",
        },
        ffa=True,
    ),
    Case(
        key="inj-coil-open",
        project="P-INJ-2203",
        year=2022,
        supplier=None,
        part="INJ-52004",
        part_name="solenoid coil",
        title="Open solenoid coils from worn winding wire guide",
        short="injector solenoid coil open circuit",
        symptom="Open-circuit coils found at engine plant incoming test: 210 PPM.",
        detection="Customer incoming test at Orion Motors engine plant.",
        root_cause="A worn wire-guide nozzle on the coil winding machine nicked the copper wire; the nick later opened "
        "under thermal stress.",
        rc_keys=["wire-guide", "nicked"],
        containment="100% coil resistance and surge test added; resistance window 15.2 ohm +/- 0.4.",
        cont_keys=["surge test", "15.2 ohm"],
        corrective="Wire guide replaced every 500,000 cycles as preventive maintenance and an inline camera inspects wire "
        "insulation.",
        ca_keys=["500,000 cycles", "camera"],
        verification="Zero open coils in 180,000 injectors after implementation.",
        lesson="Wear parts on winding machines need a replacement interval in the maintenance plan, backed by a surge test "
        "that catches damaged insulation.",
        lesson_keys=["preventive maintenance", "surge test"],
        num_q="What defect rate in PPM did the injector coil open circuit reach at the customer?",
        num_a="210 PPM",
        failure_mode="Coil open circuit",
        effect="Injector inoperative, misfire",
        cause="Wire damage from worn wire guide",
        sod_before=(7, 5, 5),
        sod_after=(7, 2, 3),
        test={
            "type": "Thermal shock",
            "standard": "NAS-TS-0120",
            "condition": "-40 C / +150 C, 15 min dwell",
            "requirement": "no open circuit after 1,000 cycles",
            "samples": 30,
            "cycles": 1000,
            "failed": 0,
        },
    ),
    Case(
        key="inj-oring-squeeze",
        project="P-INJ-2203",
        year=2023,
        supplier="SCS",
        part="INJ-52011",
        part_name="upper FKM O-ring",
        title="Fuel seepage at upper O-ring after cold start",
        short="injector upper O-ring fuel seepage",
        symptom="Fuel smell after cold starts at -25 C; 12 vehicles with seepage at the injector cup.",
        detection="Customer cold-climate fleet test.",
        root_cause="The O-ring groove depth tolerance of +/- 0.08 mm allowed only 11% squeeze at worst case; at -25 C the "
        "FKM seal shrank and lost contact.",
        rc_keys=["groove", "11% squeeze"],
        containment="Grooves measured and parts at the deep end of tolerance scrapped.",
        cont_keys=["grooves measured"],
        corrective="Groove tolerance tightened to +/- 0.04 mm to guarantee at least 16% squeeze; low-temperature FKM grade "
        "specified.",
        ca_keys=["0.04 mm", "16%"],
        verification="Cold leak test at -30 C passed on 24 injectors.",
        lesson="Run a worst-case tolerance stack for seal squeeze at the lowest temperature, including thermal shrinkage "
        "of the elastomer.",
        lesson_keys=["tolerance stack", "squeeze"],
        num_q="What was the worst-case O-ring squeeze in the injector fuel seepage case?",
        num_a="11%",
        failure_mode="Fuel seepage at O-ring",
        effect="Fuel smell, fire risk",
        cause="Low seal squeeze from groove tolerance",
        sod_before=(9, 4, 5),
        sod_after=(9, 2, 3),
        test={
            "type": "Cold leak test",
            "standard": "NAS-TS-0530",
            "condition": "-30 C, 6 bar fuel pressure",
            "requirement": "no leakage",
            "samples": 24,
            "cycles": 1,
            "failed": 0,
        },
        ecn={"what": "upper O-ring groove depth tolerance", "from": "+/- 0.08 mm", "to": "+/- 0.04 mm"},
    ),
    # ------------------------------------------------------------------ SENSOR
    Case(
        key="sns-egt-drift",
        project="P-SNS-2002",
        year=2021,
        supplier="HLS",
        part="SNS-60102",
        part_name="EGT sensing element",
        title="EGT sensor drift from moisture in MgO insulation",
        short="EGT sensor drift",
        symptom="Exhaust gas temperature readings drifted by up to +35 C after 1,000 h, causing unnecessary DPF "
        "regenerations on Halden Trucks vehicles.",
        detection="Field data analysis by the customer.",
        root_cause="Moisture absorbed by the MgO powder insulation during storage at Heliot Sensors contaminated the Pt200 "
        "element at high temperature.",
        rc_keys=["MgO", "moisture"],
        containment="Stocked sensors checked with a high-temperature calibration check.",
        cont_keys=["calibration check"],
        corrective="MgO bake-out at 400 C for 4 hours immediately before sealing; humidity-controlled storage.",
        ca_keys=["bake-out", "400 C"],
        verification="Drift below 5 C after 1,000 h at 850 C.",
        lesson="Hygroscopic materials in sensors need controlled storage and a bake-out step specified in the control plan.",
        lesson_keys=["hygroscopic", "bake-out"],
        num_q="How much did EGT sensor readings drift in the MgO moisture case?",
        num_a="+35 C",
        failure_mode="Signal drift",
        effect="Unnecessary DPF regeneration, fuel consumption",
        cause="Element contamination from moisture in insulation",
        sod_before=(6, 5, 7),
        sod_after=(6, 2, 4),
        test={
            "type": "High-temperature drift",
            "standard": "NAS-TS-0610",
            "condition": "850 C exhaust, 1,000 h",
            "requirement": "drift below 10 C",
            "samples": 8,
            "cycles": 1000,
            "failed": 0,
            "unit": "h",
        },
        ffa=True,
    ),
    Case(
        key="sns-map-water",
        project="P-SNS-2201",
        year=2022,
        supplier=None,
        part="SNS-61220",
        part_name="MAP sensor connector seal",
        title="Water ingress through damaged MAP sensor connector seal",
        short="MAP sensor water ingress",
        symptom="False boost-pressure readings and limp-home mode; corrosion found on sensor pins.",
        detection="Field returns from Vesta Automobiles; 44 returns in the first year.",
        root_cause="The connector seal lip was torn during assembly because it was pushed on dry, without lubricant.",
        rc_keys=["seal lip", "without lubricant"],
        containment="Seal visual inspection with magnification at the station.",
        cont_keys=["visual inspection"],
        corrective="Automatic lubricant dispensing (silicone-free) and a poka-yoke that blocks the press without lubricant "
        "detection.",
        ca_keys=["lubricant dispensing", "poka-yoke"],
        verification="Water spray and thermal shock sequence passed on 20 sensors.",
        lesson="Assembly aids such as lubricant must be error-proofed; they are not optional operator steps.",
        lesson_keys=["error-proofed", "lubricant"],
        num_q="How many MAP sensors were returned in the first year for water ingress?",
        num_a="44",
        failure_mode="Water ingress at connector",
        effect="Incorrect signal, limp-home",
        cause="Seal damaged at assembly",
        sod_before=(7, 5, 6),
        sod_after=(7, 2, 2),
        test={
            "type": "Water spray + thermal shock",
            "standard": "NAS-TS-0620",
            "condition": "80 bar spray after -40/+125 C",
            "requirement": "no water inside, signal within 1%",
            "samples": 20,
            "cycles": 1,
            "failed": 0,
        },
    ),
    Case(
        key="sns-fretting",
        project="P-SNS-2002",
        year=2023,
        supplier="MWC",
        part="SNS-60140",
        part_name="sensor harness terminals",
        title="Intermittent EGT signal from fretting corrosion of tin-plated terminals",
        short="sensor terminal fretting corrosion",
        symptom="Intermittent open-circuit fault codes on trucks with high engine vibration.",
        detection="Warranty data showed faults clustering on vehicles with high idle hours.",
        root_cause="Micromotion between tin-plated terminals under vibration caused fretting corrosion and rising contact "
        "resistance.",
        rc_keys=["fretting", "tin-plated"],
        containment="Dielectric grease applied to connectors in service.",
        cont_keys=["dielectric grease"],
        corrective="Terminal plating changed from tin to silver by Morrow Wire & Cable and a connector position assurance "
        "(CPA) added.",
        ca_keys=["silver", "CPA"],
        verification="Vibration test 10-2,000 Hz, 8 h per axis: contact resistance change below 10 milliohm.",
        lesson="Use silver or gold plating for low-current signal terminals in high-vibration locations; tin fretting is a "
        "known failure mode.",
        lesson_keys=["silver", "fretting"],
        num_q="What contact resistance change limit was met after the terminal plating change for sensor fretting?",
        num_a="below 10 milliohm",
        failure_mode="Intermittent contact",
        effect="Fault code, derate",
        cause="Fretting corrosion of tin plating under vibration",
        sod_before=(6, 6, 7),
        sod_after=(6, 2, 4),
        test={
            "type": "Vibration",
            "standard": "ISO 16750-3",
            "condition": "random 10-2,000 Hz, 8 h per axis, 125 C",
            "requirement": "contact resistance change below 10 milliohm",
            "samples": 12,
            "cycles": 24,
            "failed": 0,
            "unit": "h",
        },
        ecn={"what": "terminal plating", "from": "tin", "to": "silver"},
    ),
    # ------------------------------------------------------------------ INVERTER
    Case(
        key="inv-solder-fatigue",
        project="P-INV-2104",
        year=2022,
        supplier="APD",
        part="INV-70455",
        part_name="SiC power module",
        title="Power module die-attach solder fatigue causing loss of propulsion",
        short="inverter power module solder fatigue",
        symptom="Kairo EV reported loss of propulsion ('turtle mode') on 41 vehicles; the power module over-temperature "
        "fault was logged each time.",
        detection="Field failures; thermal impedance measurement on returned modules showed a 30% increase.",
        root_cause="Die-attach solder voiding of more than 15% (specification: 5% maximum) at Ardent Power Devices after a "
        "reflow profile change. Voids raised junction temperature and accelerated solder fatigue.",
        rc_keys=["voiding", "reflow profile"],
        containment="100% X-ray inspection of power modules in stock; 312 modules quarantined.",
        cont_keys=["X-ray", "312"],
        corrective="Vacuum reflow introduced at the supplier; die attach changed from SAC305 solder to sintered silver from "
        "the 2023 builds; X-ray void acceptance made a CTQ at the supplier's outgoing inspection.",
        ca_keys=["sintered silver", "vacuum reflow"],
        verification="Power cycling of 60,000 cycles at delta Tj = 100 K passed with no thermal impedance increase.",
        lesson="Die-attach voiding is a critical characteristic for power modules. Require X-ray acceptance data at the "
        "supplier and consider sintered silver for high-temperature SiC.",
        lesson_keys=["voiding", "critical characteristic"],
        num_q="How many power modules were quarantined during containment of the inverter solder fatigue issue?",
        num_a="312",
        failure_mode="Die-attach solder fatigue",
        effect="Loss of propulsion",
        cause="Solder voiding above specification",
        sod_before=(9, 5, 6),
        sod_after=(9, 2, 3),
        test={
            "type": "Power cycling",
            "standard": "AQG 324",
            "condition": "delta Tj = 100 K, ton 2 s",
            "requirement": "60,000 cycles, Rth increase below 20%",
            "samples": 6,
            "cycles": 60000,
            "failed": 0,
        },
        ecn={"what": "power module die attach", "from": "SAC305 solder", "to": "sintered silver"},
        ffa=True,
    ),
    Case(
        key="inv-dclink-cap",
        project="P-INV-2301",
        year=2023,
        supplier="QTC",
        part="INV-72031",
        part_name="DC-link film capacitor",
        title="DC-link capacitor capacitance loss under humidity",
        short="inverter DC-link capacitor degradation",
        symptom="Capacitance loss of 9% measured on DV samples after THB testing, with rising ripple current.",
        detection="Design validation THB test (85 C / 85% RH).",
        root_cause="Humidity diffused through the potting and corroded the thin metallisation of the film capacitor "
        "supplied by Qiantai Ceramics.",
        rc_keys=["metallisation", "humidity"],
        containment="PV builds held until the capacitor change was qualified.",
        cont_keys=["held"],
        corrective="Capacitor changed to a humidity-robust grade (THB grade III, segmented metallisation) and potting "
        "changed to a low-permeability epoxy.",
        ca_keys=["grade III", "epoxy"],
        verification="THB 1,000 h at 85 C / 85% RH with 1.2% capacitance loss.",
        lesson="Film capacitors in potted inverters need THB-rated grades; the potting is not a moisture barrier.",
        lesson_keys=["THB", "moisture barrier"],
        num_q="How much capacitance did the DC-link capacitor lose in the original THB test?",
        num_a="9%",
        failure_mode="Capacitance loss",
        effect="Higher ripple, reduced inverter life",
        cause="Humidity corrosion of metallisation",
        sod_before=(7, 5, 4),
        sod_after=(7, 2, 3),
        test={
            "type": "Temperature-humidity-bias (THB)",
            "standard": "IEC 60068-2-67",
            "condition": "85 C / 85% RH, 1,000 h",
            "requirement": "capacitance loss below 5%",
            "samples": 10,
            "cycles": 1000,
            "failed": 0,
            "unit": "h",
        },
    ),
    Case(
        key="inv-emc",
        project="P-INV-2104",
        year=2021,
        supplier=None,
        part="INV-70500",
        part_name="inverter DC harness and ground strap",
        title="Radiated emission exceedance in the FM band",
        short="inverter radiated emission exceedance",
        symptom="CISPR 25 radiated emission test failed in the 30-108 MHz range by 8 dB.",
        detection="EMC design validation test.",
        root_cause="Common-mode current on the DC harness because there were no Y-capacitors at the DC input, and the 120 "
        "mm ground strap was too inductive.",
        rc_keys=["Y-capacitors", "ground strap"],
        containment="Customer informed; B-sample deliveries continued with a ferrite on the DC harness.",
        cont_keys=["ferrite"],
        corrective="Two 4.7 nF Y-capacitors added at the DC input, a ferrite core integrated, and the ground strap shortened "
        "from 120 mm to 45 mm.",
        ca_keys=["4.7 nF", "45 mm"],
        verification="Re-test passed with 4 dB margin below the Class 3 limit.",
        lesson="Plan Y-capacitor footprints and a short ground path in the first PCB layout; adding them late costs a "
        "sample loop.",
        lesson_keys=["Y-capacitor", "ground path"],
        num_q="By how many dB did the inverter exceed the radiated emission limit?",
        num_a="8 dB",
        failure_mode="Radiated emission above limit",
        effect="Radio interference, homologation failure",
        cause="Common-mode current on DC harness",
        sod_before=(6, 6, 4),
        sod_after=(6, 2, 3),
        test={
            "type": "EMC radiated emissions",
            "standard": "CISPR 25 Class 3",
            "condition": "ALSE, 30-1,000 MHz",
            "requirement": "below Class 3 limit",
            "samples": 1,
            "cycles": 1,
            "failed": 0,
        },
        ecn={"what": "inverter ground strap length", "from": "120 mm", "to": "45 mm"},
    ),
    Case(
        key="inv-desat",
        project="P-INV-2104",
        year=2024,
        supplier=None,
        part="INV-70610",
        part_name="gate driver board",
        title="False desaturation trips at cold start",
        short="inverter false desaturation trips",
        symptom="Inverter shut-downs with desaturation fault at cold starts below -20 C.",
        detection="Customer winter test fleet.",
        root_cause="The desaturation blanking time of 1.2 us was too short for SiC switching transients at low "
        "temperature.",
        rc_keys=["blanking time", "1.2 us"],
        containment="Software calibration update limiting torque at cold start.",
        cont_keys=["calibration update"],
        corrective="Blanking time increased to 2.0 us and a firmware filter requires two consecutive detections.",
        ca_keys=["2.0 us", "two consecutive"],
        verification="No false trips in 3,000 cold starts at -30 C.",
        lesson="Gate-driver protection timing must be validated over the full temperature range with the actual power "
        "semiconductor technology.",
        lesson_keys=["temperature range", "protection timing"],
        num_q="What desaturation blanking time caused the false trips on the inverter?",
        num_a="1.2 us",
        failure_mode="Nuisance protection trip",
        effect="Loss of propulsion",
        cause="Blanking time too short for SiC transients",
        sod_before=(8, 4, 5),
        sod_after=(8, 2, 3),
        test={
            "type": "Cold start validation",
            "standard": "NAS-TS-0740",
            "condition": "-30 C cold soak, full-torque start",
            "requirement": "no trips in 3,000 starts",
            "samples": 2,
            "cycles": 3000,
            "failed": 0,
        },
    ),
    # ------------------------------------------------------------------ DC-DC
    Case(
        key="dcd-mlcc-crack",
        project="P-DCD-2102",
        year=2022,
        supplier="QTC",
        part="DCD-80127",
        part_name="output filter MLCC (1210)",
        title="MLCC flex cracks near the PCB break line",
        short="DC-DC converter MLCC flex cracks",
        symptom="Short circuits on the 12 V output; ICT failure rate of 0.8% at the Pune line.",
        detection="In-circuit test and 3 field returns.",
        root_cause="1210 MLCCs placed 1.2 mm from the break line cracked during pizza-cutter depaneling due to board "
        "flexing.",
        rc_keys=["depaneling", "break line"],
        containment="Boards 100% tested with a hot-spot IR scan at power-up.",
        cont_keys=["IR scan"],
        corrective="5 mm keep-out from the break line, soft-termination MLCCs from Qiantai Ceramics, and router "
        "depaneling instead of the pizza cutter.",
        ca_keys=["5 mm keep-out", "soft-termination"],
        verification="Strain gauge measurement below 300 microstrain during depaneling; zero cracks in cross-sections.",
        lesson="Keep large MLCCs away from board edges and measure strain during depaneling at process release.",
        lesson_keys=["keep-out", "strain"],
        num_q="What was the ICT failure rate caused by MLCC flex cracks on the DC-DC converter line?",
        num_a="0.8%",
        failure_mode="MLCC short circuit",
        effect="Loss of 12 V supply",
        cause="Flex crack from depaneling strain",
        sod_before=(8, 5, 5),
        sod_after=(8, 2, 3),
        test={
            "type": "Board flex / strain",
            "standard": "IPC/JEDEC-9704",
            "condition": "strain gauges near MLCCs",
            "requirement": "below 500 microstrain",
            "samples": 20,
            "cycles": 1,
            "failed": 0,
        },
        ecn={
            "what": "MLCC placement near break line",
            "from": "1.2 mm from break line",
            "to": "5 mm keep-out",
        },
    ),
    Case(
        key="dcd-core-crack",
        project="P-DCD-2102",
        year=2023,
        supplier=None,
        part="DCD-80210",
        part_name="transformer ferrite core",
        title="Transformer ferrite core cracking from potting stress",
        short="DC-DC transformer core crack",
        symptom="Efficiency drop and audible noise after thermal cycling; cracked ferrite cores found.",
        detection="Requalification test after a potting supplier change.",
        root_cause="The new rigid potting compound had a CTE mismatch with the ferrite core and built up stress during "
        "thermal cycling.",
        rc_keys=["CTE mismatch", "potting"],
        containment="Units potted with the new compound were quarantined.",
        cont_keys=["quarantined"],
        corrective="Soft silicone potting (Shore A 30) and a compliant core adhesive.",
        ca_keys=["Shore A 30", "silicone"],
        verification="4,000 thermal cycles without cracks.",
        lesson="Potting material changes require thermal cycling requalification of every embedded ceramic or ferrite "
        "part.",
        lesson_keys=["requalification", "ferrite"],
        num_q="How many thermal cycles did the DC-DC transformer survive after the potting change?",
        num_a="4,000",
        failure_mode="Core crack",
        effect="Efficiency loss, noise",
        cause="CTE mismatch with potting",
        sod_before=(6, 4, 5),
        sod_after=(6, 2, 3),
        test={
            "type": "Thermal cycling",
            "standard": "NAS-TS-0412",
            "condition": "-40 C / +125 C",
            "requirement": "no cracks after 3,000 cycles",
            "samples": 8,
            "cycles": 4000,
            "failed": 0,
        },
    ),
    Case(
        key="dcd-ripple",
        project="P-DCD-2102",
        year=2024,
        supplier=None,
        part="DCD-80305",
        part_name="control firmware",
        title="Output ripple above specification at light load",
        short="DC-DC output ripple",
        symptom="Output ripple of 450 mV at light load against a 200 mV specification; flicker on dashboard lights.",
        detection="Customer vehicle test.",
        root_cause="Burst-mode operation at light load created low-frequency ripple the output filter could not "
        "attenuate.",
        rc_keys=["burst-mode", "light load"],
        containment="Software parameter change to disable burst mode below 5% load (efficiency penalty accepted).",
        cont_keys=["disable burst mode"],
        corrective="Firmware v3.2 raised the burst threshold and two 22 uF capacitors were added to the output filter.",
        ca_keys=["v3.2", "22 uF"],
        verification="Ripple measured at 140 mV across the full load range.",
        lesson="Specify ripple over the whole load range, including light-load and burst-mode regions.",
        lesson_keys=["whole load range"],
        num_q="What output ripple did the DC-DC converter show at light load before the fix?",
        num_a="450 mV",
        failure_mode="Excess output ripple",
        effect="Light flicker, EMC risk",
        cause="Burst-mode at light load",
        sod_before=(5, 5, 5),
        sod_after=(5, 2, 3),
        test={
            "type": "Output ripple",
            "standard": "NAS-TS-0810",
            "condition": "0-100% load sweep, 9-16 V",
            "requirement": "ripple below 200 mV",
            "samples": 3,
            "cycles": 1,
            "failed": 0,
        },
    ),
    # ------------------------------------------------------------------ BMS
    Case(
        key="bms-voltage-drift",
        project="P-BMS-2103",
        year=2022,
        supplier="LPW",
        part="BMS-90114",
        part_name="analog front-end PCBA",
        title="Cell voltage measurement drift from flux residue",
        short="BMS cell voltage measurement drift",
        symptom="Cell voltage readings drifted by up to 12 mV after humidity exposure, causing incorrect state-of-charge.",
        detection="Kairo EV battery validation.",
        root_cause="No-clean flux residue under the analog front-end created leakage paths once humidity was absorbed.",
        rc_keys=["flux residue", "leakage"],
        containment="Affected boards cleaned and re-tested.",
        cont_keys=["cleaned"],
        corrective="Wash process added at Lumen PCB Works with ionic contamination limit of 1.56 ug/cm2 NaCl equivalent, "
        "and conformal coating over the AFE area.",
        ca_keys=["ionic contamination", "conformal coating"],
        verification="Drift below 2 mV after 500 h of damp heat.",
        lesson="High-impedance measurement circuits need cleanliness control and conformal coating; no-clean flux is not "
        "no-risk.",
        lesson_keys=["cleanliness", "no-clean"],
        num_q="How large was the BMS cell voltage measurement drift?",
        num_a="12 mV",
        failure_mode="Measurement drift",
        effect="Wrong SOC, possible over-charge",
        cause="Leakage from flux residue",
        sod_before=(9, 4, 6),
        sod_after=(9, 2, 3),
        test={
            "type": "Damp heat",
            "standard": "IEC 60068-2-78",
            "condition": "85 C / 85% RH, 500 h",
            "requirement": "drift below 5 mV",
            "samples": 6,
            "cycles": 500,
            "failed": 0,
            "unit": "h",
        },
    ),
    Case(
        key="bms-can-loss",
        project="P-BMS-2103",
        year=2023,
        supplier=None,
        part="BMS-90201",
        part_name="CAN interface",
        title="Intermittent CAN communication loss during BCI testing",
        short="BMS CAN communication loss",
        symptom="CAN bus-off events during bulk current injection at 60 mA.",
        detection="EMC immunity validation (ISO 11452-4 BCI).",
        root_cause="The CAN interface lacked split termination and a common-mode choke, so injected common-mode noise "
        "corrupted frames.",
        rc_keys=["split termination", "common-mode choke"],
        containment="None required; issue found before SOP.",
        cont_keys=["before SOP"],
        corrective="Split termination of 2 x 60 ohm with a 4.7 nF capacitor and a common-mode choke added to the CAN "
        "lines.",
        ca_keys=["2 x 60 ohm", "choke"],
        verification="BCI passed at 100 mA with no bus-off.",
        lesson="Use the reference CAN interface circuit with split termination and a choke on every ECU from the first "
        "layout.",
        lesson_keys=["reference CAN interface"],
        num_q="At what BCI current did the BMS lose CAN communication?",
        num_a="60 mA",
        failure_mode="Communication loss",
        effect="Battery contactor opening, loss of propulsion",
        cause="Insufficient CAN common-mode immunity",
        sod_before=(8, 4, 4),
        sod_after=(8, 2, 3),
        test={
            "type": "EMC bulk current injection",
            "standard": "ISO 11452-4",
            "condition": "1-400 MHz, 100 mA",
            "requirement": "no communication loss",
            "samples": 2,
            "cycles": 1,
            "failed": 0,
        },
    ),
    Case(
        key="bms-pin-pushout",
        project="P-BMS-2103",
        year=2021,
        supplier="MWC",
        part="BMS-90330",
        part_name="cell-sense harness connector",
        title="Terminal push-out in the cell-sense connector",
        short="BMS connector pin push-out",
        symptom="Open cell-sense lines detected at battery end-of-line test; 27 packs affected.",
        detection="Battery pack end-of-line test at Chennai.",
        root_cause="Terminal locking lances were deformed by a worn insertion tool at Morrow Wire & Cable, so terminals "
        "pushed out when the connector was mated.",
        rc_keys=["locking lance", "insertion tool"],
        containment="All harness connectors pull-tested at 50 N before assembly.",
        cont_keys=["pull-tested", "50 N"],
        corrective="Terminal position assurance (TPA) added to the connector and the insertion tool put on a replacement "
        "interval.",
        ca_keys=["TPA", "replacement interval"],
        verification="Zero push-outs in 5,400 packs.",
        lesson="Use connectors with TPA for safety-relevant sense lines and require a push-back test at the harness "
        "supplier.",
        lesson_keys=["TPA", "push-back test"],
        num_q="How many battery packs were affected by the BMS connector pin push-out?",
        num_a="27",
        failure_mode="Terminal push-out",
        effect="Loss of cell monitoring",
        cause="Deformed locking lance",
        sod_before=(8, 5, 5),
        sod_after=(8, 2, 2),
        test={
            "type": "Terminal retention",
            "standard": "USCAR-2",
            "condition": "axial pull after mating",
            "requirement": "retention above 50 N",
            "samples": 60,
            "cycles": 1,
            "failed": 0,
        },
    ),
    Case(
        key="bms-watchdog",
        project="P-BMS-2103",
        year=2024,
        supplier=None,
        part="BMS-90412",
        part_name="BMS firmware",
        title="Watchdog resets during over-the-air update",
        short="BMS watchdog reset during OTA",
        symptom="BMS ECU resets during OTA updates, aborting the update on 3% of vehicles.",
        detection="Customer OTA campaign telemetry.",
        root_cause="Flash sector erase blocked the CPU for up to 80 ms, longer than the 50 ms watchdog timeout.",
        rc_keys=["flash", "50 ms"],
        containment="OTA campaign paused.",
        cont_keys=["paused"],
        corrective="Background (non-blocking) flash erase with the watchdog serviced between sector operations.",
        ca_keys=["non-blocking", "watchdog serviced"],
        verification="10,000 OTA cycles on the bench without reset.",
        lesson="Any long blocking operation must be analysed against watchdog timing, especially rarely-run paths such as "
        "OTA.",
        lesson_keys=["watchdog timing"],
        num_q="On what share of vehicles did the BMS OTA update abort?",
        num_a="3%",
        failure_mode="ECU reset during update",
        effect="Update failure, vehicle unavailable",
        cause="Blocking flash erase longer than watchdog timeout",
        sod_before=(6, 5, 5),
        sod_after=(6, 2, 3),
        test={
            "type": "OTA endurance",
            "standard": "NAS-TS-0920",
            "condition": "bench, full image",
            "requirement": "10,000 updates without reset",
            "samples": 4,
            "cycles": 10000,
            "failed": 0,
        },
    ),
    # ------------------------------------------------------------------ WIPER MOTOR
    Case(
        key="wpm-gear-wear",
        project="P-WPM-2003",
        year=2021,
        supplier="VLX",
        part="WPM-11205",
        part_name="worm gear",
        title="Worm gear wear after switch to recycled POM",
        short="wiper motor worm gear wear",
        symptom="Grinding noise and park position drift after about 400,000 wipe cycles.",
        detection="Halden Trucks fleet complaints; 58 returns.",
        root_cause="Veltrix Polymers switched the gear material to a recycled POM grade with lower wear resistance.",
        rc_keys=["recycled POM"],
        containment="Recycled-grade lots identified by material certificates and quarantined.",
        cont_keys=["material certificates"],
        corrective="Virgin POM specified by grade name on the drawing; material certificate check at incoming.",
        ca_keys=["virgin POM"],
        verification="Gear wear test of 1.5 million cycles passed.",
        lesson="Specify polymer grades by name on the drawing and require notification for any regrind or recycled "
        "content.",
        lesson_keys=["grade", "recycled"],
        num_q="How many wiper motors were returned for worm gear wear?",
        num_a="58",
        failure_mode="Gear tooth wear",
        effect="Noise, wiper park position error",
        cause="Lower wear resistance of recycled POM",
        sod_before=(6, 5, 6),
        sod_after=(6, 2, 4),
        test={
            "type": "Wiper endurance",
            "standard": "NAS-TS-1110",
            "condition": "wet/dry cycling, 23 C",
            "requirement": "1.5 million cycles",
            "samples": 6,
            "cycles": 1500000,
            "failed": 0,
        },
        ffa=True,
    ),
    Case(
        key="wpm-water",
        project="P-WPM-2003",
        year=2022,
        supplier=None,
        part="WPM-11310",
        part_name="breather vent membrane",
        title="Water ingress through misaligned breather vent",
        short="wiper motor water ingress",
        symptom="Motors stopped working after car washes; corroded brushes and commutator.",
        detection="Warranty returns, 33 units.",
        root_cause="The ePTFE breather membrane was welded off-centre, leaving a leak path around the vent.",
        rc_keys=["ePTFE", "off-centre"],
        containment="Vent weld inspected 100% with a fixture gauge.",
        cont_keys=["fixture gauge"],
        corrective="Vision system checks membrane position after welding; weld nest redesigned with locating pins.",
        ca_keys=["vision system", "locating pins"],
        verification="High-pressure water spray at 80 bar passed on 15 motors.",
        lesson="Membrane welds are critical sealing features and need automatic position verification.",
        lesson_keys=["position verification"],
        num_q="How many wiper motors were returned for water ingress through the breather vent?",
        num_a="33",
        failure_mode="Water ingress",
        effect="Motor failure, loss of wiping",
        cause="Misaligned breather membrane weld",
        sod_before=(8, 4, 6),
        sod_after=(8, 2, 2),
        test={
            "type": "High-pressure water spray",
            "standard": "ISO 20653",
            "condition": "80 bar, 80 C, 4 angles",
            "requirement": "no water inside",
            "samples": 15,
            "cycles": 1,
            "failed": 0,
        },
    ),
    Case(
        key="wpm-park-switch",
        project="P-WPM-2003",
        year=2023,
        supplier="SCS",
        part="WPM-11402",
        part_name="park switch contacts",
        title="Park switch failures from sulphur outgassing of the gasket",
        short="wiper park switch contact failure",
        symptom="Wipers stop at random positions; contact bounce on the park switch.",
        detection="Field returns; black film found on silver contacts.",
        root_cause="The sulphur-cured EPDM gasket from Seacrest Seals released sulphur, forming silver sulphide on the "
        "switch contacts.",
        rc_keys=["sulphur", "silver sulphide"],
        containment="Gaskets replaced on motors in stock.",
        cont_keys=["gaskets replaced"],
        corrective="Peroxide-cured EPDM gasket specified.",
        ca_keys=["peroxide-cured"],
        verification="Sulphur outgassing test and 1,000 h at 85 C with contact resistance stable.",
        lesson="Materials near silver contacts must be sulphur-free; add an outgassing check to material approval.",
        lesson_keys=["sulphur-free", "outgassing"],
        num_q="What type of EPDM gasket replaced the sulphur-cured gasket in the wiper motor?",
        num_a="peroxide-cured EPDM",
        failure_mode="Switch contact failure",
        effect="Wiper stops out of park",
        cause="Silver sulphide from gasket outgassing",
        sod_before=(6, 4, 6),
        sod_after=(6, 2, 4),
        test={
            "type": "High-temperature storage",
            "standard": "NAS-TS-1120",
            "condition": "85 C, 1,000 h",
            "requirement": "contact resistance below 50 milliohm",
            "samples": 10,
            "cycles": 1000,
            "failed": 0,
            "unit": "h",
        },
        ecn={
            "what": "motor cover gasket material",
            "from": "sulphur-cured EPDM",
            "to": "peroxide-cured EPDM",
        },
    ),
    # ------------------------------------------------------------------ EPS MOTOR
    Case(
        key="eps-torque-ripple",
        project="P-EPS-2102",
        year=2022,
        supplier="BOM",
        part="EPS-12108",
        part_name="rotor magnet assembly",
        title="Notchy steering from magnet misalignment and high cogging torque",
        short="EPS motor torque ripple",
        symptom="Drivers felt notchy steering at parking speeds.",
        detection="Customer subjective evaluation; cogging torque measured at 38 mNm against a 20 mNm limit.",
        root_cause="Rotor magnet segments from Brandt-Ostwald Magnetics shifted during adhesive cure because the bonding "
        "fixture had worn locating features.",
        rc_keys=["magnet", "adhesive cure"],
        containment="100% cogging torque test at end of line.",
        cont_keys=["cogging torque test"],
        corrective="Bonding fixture redesigned with hardened locators and magnet skew of 7.5 degrees introduced.",
        ca_keys=["7.5 degrees", "fixture"],
        verification="Cogging torque reduced to 14 mNm.",
        lesson="Magnet position is a critical characteristic for EPS motors; control bonding fixtures like gauges.",
        lesson_keys=["critical characteristic", "fixtures"],
        num_q="What cogging torque was measured on the EPS motor before the magnet fix?",
        num_a="38 mNm",
        failure_mode="Torque ripple",
        effect="Notchy steering feel",
        cause="Magnet segment misalignment",
        sod_before=(6, 5, 5),
        sod_after=(6, 2, 3),
        test={
            "type": "Cogging torque",
            "standard": "NAS-TS-1210",
            "condition": "0.5 rpm, 23 C",
            "requirement": "below 20 mNm",
            "samples": 30,
            "cycles": 1,
            "failed": 0,
        },
        ecn={"what": "rotor magnet skew", "from": "no skew", "to": "7.5 degree skew"},
    ),
    Case(
        key="eps-hall-eos",
        project="P-EPS-2102",
        year=2023,
        supplier=None,
        part="EPS-12230",
        part_name="Hall sensor board",
        title="Hall sensor damage from load-dump transients",
        short="EPS Hall sensor failure",
        symptom="Loss of steering assist with Hall sensor plausibility fault; 9 vehicles.",
        detection="Field failures; the analysis found electrical overstress on the Hall IC supply pin.",
        root_cause="The Hall sensor supply had no transient protection, so load-dump pulses exceeded the IC's absolute "
        "maximum rating.",
        rc_keys=["transient protection", "load-dump"],
        containment="Affected lot traced; no containment possible in the field beyond monitoring.",
        cont_keys=["monitoring"],
        corrective="TVS diode and 100 ohm series resistor added to the Hall supply.",
        ca_keys=["TVS", "100 ohm"],
        verification="ISO 7637-2 pulse tests passed on 10 boards.",
        lesson="Every off-board-supplied sensor needs transient protection sized for ISO 7637 pulses.",
        lesson_keys=["ISO 7637", "transient protection"],
        num_q="How many vehicles lost steering assist from EPS Hall sensor failures?",
        num_a="9",
        failure_mode="Hall sensor failure",
        effect="Loss of steering assist",
        cause="Electrical overstress from transients",
        sod_before=(9, 4, 5),
        sod_after=(9, 2, 3),
        test={
            "type": "Electrical transients",
            "standard": "ISO 7637-2",
            "condition": "pulses 1, 2a, 3a/3b",
            "requirement": "no damage, status A/C",
            "samples": 10,
            "cycles": 1,
            "failed": 0,
        },
        ffa=True,
    ),
    Case(
        key="eps-bearing-grease",
        project="P-EPS-2102",
        year=2024,
        supplier="CBR",
        part="EPS-12315",
        part_name="rear ball bearing",
        title="Bearing growl after cold soak from unannounced grease change",
        short="EPS bearing noise",
        symptom="Growl noise from the EPS motor for the first minutes after a cold soak below -20 C.",
        detection="Customer complaints in the first winter; 21 returns.",
        root_cause="Castell Bearings changed the bearing grease to a different base oil without notification; the new "
        "grease channelled poorly at low temperature.",
        rc_keys=["grease", "without notification"],
        containment="Bearings with the new grease identified by lot code and blocked.",
        cont_keys=["lot code"],
        corrective="Grease type and fill quantity specified on the bearing drawing; change notification required under "
        "PPAP.",
        ca_keys=["grease type", "PPAP"],
        verification="Cold-start noise test at -30 C passed on 12 motors.",
        lesson="Bearing grease is part of the design; lock it on the drawing and in the supplier's PPAP.",
        lesson_keys=["grease", "PPAP"],
        num_q="How many EPS motors were returned for bearing noise after cold soak?",
        num_a="21",
        failure_mode="Bearing noise",
        effect="Customer complaint (NVH)",
        cause="Grease change with poor low-temperature properties",
        sod_before=(5, 5, 6),
        sod_after=(5, 2, 4),
        test={
            "type": "Cold-start NVH",
            "standard": "NAS-TS-1240",
            "condition": "-30 C soak 12 h",
            "requirement": "no audible growl",
            "samples": 12,
            "cycles": 1,
            "failed": 0,
        },
    ),
]
CASE = {c.key: c for c in CASES}

# Extra DFMEA rows per component (not linked to a case).
EXTRA_FMEA = {
    "RAD": [
        ("Fin collapse", "Reduced cooling", "Fin pitch too fine for handling", 5, 4, 5),
        ("Mounting bracket fatigue", "Radiator detachment", "Vibration resonance", 8, 3, 4),
        ("Drain plug leak", "Coolant loss", "Thread damage at assembly", 6, 3, 3),
    ],
    "HVC": [
        ("Mode door rattle", "Noise", "Clearance at pivot", 4, 4, 6),
        ("Heater core leak", "Coolant in cabin", "Braze joint defect", 7, 3, 4),
        ("Filter bypass", "Poor air quality", "Filter frame gap", 5, 3, 5),
    ],
    "CMP": [
        ("Inverter board overheating", "Compressor shutdown", "Thermal interface voids", 7, 4, 5),
        ("Check valve sticking", "Noise", "Contamination", 5, 3, 6),
        ("Mount bushing crack", "Vibration transfer", "Rubber ageing", 5, 3, 5),
    ],
    "INJ": [
        ("Armature wear", "Flow shift", "Insufficient hardness", 7, 3, 5),
        ("Connector corrosion", "Open circuit", "Seal damage", 7, 3, 4),
        ("Spray pattern deviation", "Emissions", "Hole burr", 7, 3, 3),
    ],
    "SNS": [
        ("Sensor housing crack", "Signal loss", "Over-torque at installation", 6, 3, 4),
        ("Cable chafing", "Open circuit", "Routing near sharp edge", 6, 4, 5),
        ("Calibration offset", "Wrong reading", "EOL calibration error", 6, 3, 3),
    ],
    "INV": [
        ("Busbar joint overheating", "Derating", "Low screw preload", 8, 3, 5),
        ("Coolant leak into housing", "Short circuit", "Gasket compression set", 9, 2, 4),
        ("Current sensor offset", "Torque error", "Temperature drift", 7, 3, 4),
    ],
    "DCD": [
        ("Output diode failure", "Loss of 12 V", "Thermal overstress", 8, 3, 4),
        ("Coolant plate leak", "Short circuit", "Porosity in casting", 9, 2, 3),
        ("Input fuse nuisance blow", "Loss of 12 V", "Inrush current", 6, 3, 4),
    ],
    "BMS": [
        ("Temperature sensor open", "Loss of cell temperature", "Cracked NTC", 8, 3, 3),
        ("Isolation monitor false alarm", "Vehicle not ready", "Leakage path", 7, 3, 5),
        ("Contactor driver failure", "Cannot connect battery", "Driver overcurrent", 8, 2, 4),
    ],
    "WPM": [
        ("Brush wear", "Motor stops", "High current at stall", 6, 3, 5),
        ("Linkage ball joint wear", "Rattle", "Lubrication loss", 4, 4, 5),
        ("PCB corrosion", "Erratic speed", "Condensation", 6, 3, 5),
    ],
    "EPS": [
        ("Phase winding short", "Loss of assist", "Insulation damage", 9, 2, 4),
        ("Position sensor offset", "Torque steer", "Magnet ageing", 8, 3, 4),
        ("Connector fretting", "Intermittent assist", "Vibration", 8, 3, 5),
    ],
}

# Work instructions with a superseded revision: (id, plant, comp, title, rev A spec, rev B spec, reason)
WORK_INSTRUCTIONS = [
    (
        "WI-CHN-012",
        "CHN",
        "INV",
        "Power module mounting and torque",
        "8.0 Nm",
        "9.5 Nm",
        "ECN after busbar joint overheating risk review: higher preload for the thicker sintered-silver module baseplate",
    ),
    (
        "WI-TLC-007",
        "TLC",
        "WPM",
        "Wiper motor gearbox cover assembly",
        "2.2 Nm",
        "2.6 Nm",
        "Cover gasket changed to peroxide-cured EPDM, which needs higher clamp load",
    ),
    (
        "WI-PN2-021",
        "PN2",
        "DCD",
        "DC-DC converter potting and cure",
        "cure 60 min at 80 C",
        "cure 90 min at 70 C",
        "Soft silicone potting needs a lower-temperature, longer cure",
    ),
]
